# Generated by Django 5.0.7 on 2024-07-25 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
