# Generated by Django 5.0.7 on 2024-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
